name: Example pynt yml 
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "API Security tests"

env:
  PYNT_CREDENTIALS: ${{ secrets.YOURPYNTID }}

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli 
    - name: get goat collection 
      run: | 
        curl https://raw.githubusercontent.com/apoorvau6/pynt/main/Mynewcollection.postman_collection.json 
    - name: run pynt with newman integration 
      run: | 
        pynt newman --collection https://raw.githubusercontent.com/apoorvau6/pynt/main/Mynewcollection.postman_collection.json --reporters
